In [1]:
import pandas as pd
import numpy as np
import mysql.connector

In [2]:
con = mysql.connector.connect(host="localhost",user="root",password="Root#123",database="employeedb")
print(con)

<mysql.connector.connection.MySQLConnection object at 0x73c5a45e2570>

In [3]:
sql = "select * from employee"
df = pd.read_sql(sql=sql,con=con)
df

/tmp/ipykernel_5377/1566439657.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql=sql,con=con)

,employee_id,employee_name,email,salary,experience,city_id
0,1,Amit Sharma,amit.sharma@gmail.com,55000.0,3,1
1,2,Priya Verma,priya.verma@gmail.com,62000.0,4,2
2,3,Rahul Singh,rahul.singh@gmail.com,48000.0,2,3
3,4,Neha Patel,neha.patel@gmail.com,75000.0,5,4
4,5,Rohit Joshi,rohit.joshi@gmail.com,68000.0,4,5
5,6,Sneha Mehta,sneha.mehta@gmail.com,82000.0,6,6
6,7,John Smith,john.smith@gmail.com,95000.0,7,7
7,8,David Brown,david.brown@gmail.com,88000.0,6,8
8,9,Emily Wilson,emily.wilson@gmail.com,92000.0,8,9
9,10,Michael Davis,michael.davis@gmail.com,78000.0,5,10
10,11,Daniel Miller,daniel.miller@gmail.com,85000.0,6,11
11,12,Sophia Anderson,sophia.anderson@gmail.com,91000.0,7,13
12,13,Oliver Taylor,oliver.taylor@gmail.com,73000.0,4,15
13,14,Emma Thomas,emma.thomas@gmail.com,79000.0,5,17
14,15,Lucas Martin,lucas.martin@gmail.com,69000.0,3,19
15,16,Isabella Garcia,isabella.garcia@gmail.com,87000.0,6,21
16,17,James Wilson,james.wilson@gmail.com,99000.0,8,23
17,18,Mia Anderson,mia.anderson@gmail.com,72000.0,4,29
18,19,William Moore,william.moore@gmail.com,93000.0,7,35
19,20,Charlotte Clark,charlotte.clark@gmail.com,81000.0,5,43

In [4]:
sql = "select employee.employee_id,employee.employee_name,employee.salary,employee.experience,city.city_name from employee inner join city on employee.city_id = city.city_id"
df = pd.read_sql(sql=sql,con=con)
df

/tmp/ipykernel_5377/1003095318.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql=sql,con=con)

    employee_id    employee_name   salary  experience      city_name
0             1      Amit Sharma  55000.0           3         Indore
1             2      Priya Verma  62000.0           4         Bhopal
2             3      Rahul Singh  48000.0           2       Jabalpur
3             4       Neha Patel  75000.0           5         Mumbai
4             5      Rohit Joshi  68000.0           4           Pune
5             6      Sneha Mehta  82000.0           6         Nagpur
6             7       John Smith  95000.0           7    Los Angeles
7             8      David Brown  88000.0           6  San Francisco
8             9     Emily Wilson  92000.0           8      San Diego
9            10    Michael Davis  78000.0           5        Houston
10           11    Daniel Miller  85000.0           6         Dallas
11           12  Sophia Anderson  91000.0           7        Toronto
12           13    Oliver Taylor  73000.0           4      Vancouver
13           14      Emma Thomas  79000.0           5         Sydney
14           15     Lucas Martin  69000.0           3      Melbourne
15           16  Isabella Garcia  87000.0           6         London
16           17     James Wilson  99000.0           8      Edinburgh
17           18     Mia Anderson  72000.0           4     Versailles
18           19    William Moore  93000.0           7          Sakai
19           20  Charlotte Clark  81000.0           5         Al Ain

In [5]:
df1 = pd.read_sql("select employee_id,employee_name,salary,experience,city_id from employee",con = con)
df1

/tmp/ipykernel_5377/3524928982.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df1 = pd.read_sql("select employee_id,employee_name,salary,experience,city_id from employee",con = con)

    employee_id    employee_name   salary  experience  city_id
0             1      Amit Sharma  55000.0           3        1
1             2      Priya Verma  62000.0           4        2
2             3      Rahul Singh  48000.0           2        3
3             4       Neha Patel  75000.0           5        4
4             5      Rohit Joshi  68000.0           4        5
5             6      Sneha Mehta  82000.0           6        6
6             7       John Smith  95000.0           7        7
7             8      David Brown  88000.0           6        8
8             9     Emily Wilson  92000.0           8        9
9            10    Michael Davis  78000.0           5       10
10           11    Daniel Miller  85000.0           6       11
11           12  Sophia Anderson  91000.0           7       13
12           13    Oliver Taylor  73000.0           4       15
13           14      Emma Thomas  79000.0           5       17
14           15     Lucas Martin  69000.0           3       19
15           16  Isabella Garcia  87000.0           6       21
16           17     James Wilson  99000.0           8       23
17           18     Mia Anderson  72000.0           4       29
18           19    William Moore  93000.0           7       35
19           20  Charlotte Clark  81000.0           5       43

In [6]:
df2 = pd.read_sql("select city_id,city_name,state_id from city",con=con)
df2

/tmp/ipykernel_5377/2216724923.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2 = pd.read_sql("select city_id,city_name,state_id from city",con=con)

    city_id       city_name  state_id
0        42       Abu Dhabi        20
1        43          Al Ain        20
2        12          Austin         4
3        39           Bedok        18
4        27          Berlin        12
5         2          Bhopal         1
6        37     Bukit Timah        17
7        11          Dallas         4
8        40           Dubai        19
9        23       Edinburgh        10
10       20         Geelong         8
11       24         Glasgow        10
12       33        Hachioji        15
13       10         Houston         4
14        1          Indore         1
15        3        Jabalpur         1
16       41        Jumeirah        19
17       21          London         9
18        7     Los Angeles         3
19       22      Manchester         9
20       30       Marseille        14
21       19       Melbourne         8
22        4          Mumbai         2
23       25          Munich        11
24        6          Nagpur         2
25       18       Newcastle         7
26       31            Nice        14
27       26       Nuremberg        11
28       34           Osaka        16
29       14          Ottawa         5
30       28           Paris        13
31        5            Pune         2
32       35           Sakai        16
33        9       San Diego         3
34        8   San Francisco         3
35       36  Singapore City        17
36       17          Sydney         7
37       38        Tampines        18
38       32           Tokyo        15
39       13         Toronto         5
40       15       Vancouver         6
41       29      Versailles        13
42       16        Victoria         6

In [7]:
df3 = pd.merge(df1,df2,on="city_id", how="inner")
df3

,employee_id,employee_name,salary,experience,city_id,city_name,state_id
0,1,Amit Sharma,55000.0,3,1,Indore,1
1,2,Priya Verma,62000.0,4,2,Bhopal,1
2,3,Rahul Singh,48000.0,2,3,Jabalpur,1
3,4,Neha Patel,75000.0,5,4,Mumbai,2
4,5,Rohit Joshi,68000.0,4,5,Pune,2
5,6,Sneha Mehta,82000.0,6,6,Nagpur,2
6,7,John Smith,95000.0,7,7,Los Angeles,3
7,8,David Brown,88000.0,6,8,San Francisco,3
8,9,Emily Wilson,92000.0,8,9,San Diego,3
9,10,Michael Davis,78000.0,5,10,Houston,4
10,11,Daniel Miller,85000.0,6,11,Dallas,4
11,12,Sophia Anderson,91000.0,7,13,Toronto,5
12,13,Oliver Taylor,73000.0,4,15,Vancouver,6
13,14,Emma Thomas,79000.0,5,17,Sydney,7
14,15,Lucas Martin,69000.0,3,19,Melbourne,8
15,16,Isabella Garcia,87000.0,6,21,London,9
16,17,James Wilson,99000.0,8,23,Edinburgh,10
17,18,Mia Anderson,72000.0,4,29,Versailles,13
18,19,William Moore,93000.0,7,35,Sakai,16
19,20,Charlotte Clark,81000.0,5,43,Al Ain,20

In [8]:
from sqlalchemy import create_engine

In [9]:
engine = create_engine("mysql+pymysql://root:Root#123@localhost:3306/employeedb")
print(engine)

Engine(mysql+pymysql://root:***@localhost:3306/employeedb)

In [11]:
df = pd.read_sql("select * from employee",engine)
df

,employee_id,employee_name,email,salary,experience,city_id
0,1,Amit Sharma,amit.sharma@gmail.com,55000.0,3,1
1,2,Priya Verma,priya.verma@gmail.com,62000.0,4,2
2,3,Rahul Singh,rahul.singh@gmail.com,48000.0,2,3
3,4,Neha Patel,neha.patel@gmail.com,75000.0,5,4
4,5,Rohit Joshi,rohit.joshi@gmail.com,68000.0,4,5
5,6,Sneha Mehta,sneha.mehta@gmail.com,82000.0,6,6
6,7,John Smith,john.smith@gmail.com,95000.0,7,7
7,8,David Brown,david.brown@gmail.com,88000.0,6,8
8,9,Emily Wilson,emily.wilson@gmail.com,92000.0,8,9
9,10,Michael Davis,michael.davis@gmail.com,78000.0,5,10
10,11,Daniel Miller,daniel.miller@gmail.com,85000.0,6,11
11,12,Sophia Anderson,sophia.anderson@gmail.com,91000.0,7,13
12,13,Oliver Taylor,oliver.taylor@gmail.com,73000.0,4,15
13,14,Emma Thomas,emma.thomas@gmail.com,79000.0,5,17
14,15,Lucas Martin,lucas.martin@gmail.com,69000.0,3,19
15,16,Isabella Garcia,isabella.garcia@gmail.com,87000.0,6,21
16,17,James Wilson,james.wilson@gmail.com,99000.0,8,23
17,18,Mia Anderson,mia.anderson@gmail.com,72000.0,4,29
18,19,William Moore,william.moore@gmail.com,93000.0,7,35
19,20,Charlotte Clark,charlotte.clark@gmail.com,81000.0,5,43

In [12]:
from pymongo import MongoClient

In [14]:
client = MongoClient("mongodb://localhost:27017/")
print(client)
db = client["empdb"]
print(db)

MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True)
Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'empdb')

In [17]:
data = db["employee"].find()
print(data)
df = pd.DataFrame(data)
df

<pymongo.synchronous.cursor.Cursor object at 0x73c589705160>

                        _id            name  salary       skill  age  gender
0  6a82f486031ce9179b6efe49    Rahul Sharma   65000  JavaScript   28    Male
1  6a82f486031ce9179b6efe4e      Neha Joshi   62000     Angular   25  Female
2  6a82f486031ce9179b6efe51  Karan Malhotra   55000         SQL   24    Male

In [20]:
data = db["employee"].find({},{"name":1,"salary":1,"skill":1,"age":1,"gender":1,"_id":0})
df = pd.DataFrame(data)
df

             name  salary       skill  age  gender
0    Rahul Sharma   65000  JavaScript   28    Male
1      Neha Joshi   62000     Angular   25  Female
2  Karan Malhotra   55000         SQL   24    Male

In [22]:
data = db["user"].find()
df = pd.DataFrame(data)
df

,_id,name,age,gender,address,city
0,6ab4aee10f580a22075ba574,Amit Sharma,28,Male,"{'house_no': 'A-102', 'street': 'Vijay Nagar',...",Indore
1,6ab4aee10f580a22075ba575,Priya Verma,25,Female,"{'house_no': 'B-205', 'street': 'MG Road', 'po...",Indore
2,6ab4aee10f580a22075ba576,Rahul Singh,32,Male,"{'house_no': 'C-301', 'street': 'Arera Colony'...",Bhopal
3,6ab4aee10f580a22075ba577,Sneha Patel,27,Female,"{'house_no': 'D-405', 'street': 'Palasia', 'po...",Indore
4,6ab4aee10f580a22075ba578,Rohit Joshi,35,Male,"{'house_no': 'E-108', 'street': 'Civil Lines',...",Jabalpur
5,6ab4aee10f580a22075ba579,Neha Gupta,24,Female,"{'house_no': 'F-212', 'street': 'Shivaji Nagar...",Nagpur
6,6ab4aee10f580a22075ba57a,Vikas Mehta,30,Male,"{'house_no': 'G-502', 'street': 'Baner Road', ...",Pune
7,6ab4aee10f580a22075ba57b,Kavita Rao,29,Female,"{'house_no': 'H-304', 'street': 'Indiranagar',...",Bangalore
8,6ab4aee10f580a22075ba57c,Arjun Malhotra,38,Male,"{'house_no': 'I-601', 'street': 'Andheri West'...",Mumbai
9,6ab4aee10f580a22075ba57d,Pooja Mishra,26,Female,"{'house_no': 'J-209', 'street': 'Gomti Nagar',...",Lucknow

In [26]:
df["address"]
df.dtypes

_id        object
name          str
age         int64
gender        str
address    object
city          str
dtype: object

In [32]:
df
df["house_no"] = df["address"].map(lambda x: x["house_no"])
df["street"] = df["address"].map(lambda x: x["street"])
df["postal_code"]= df["address"].map(lambda x: x["postal_code"])
df["landmark"] = df["address"].map(lambda x: x["landmark"])
#df.drop(columns=["address"],inplace=True)
df

KeyError: 'address'

In [37]:
data = db["users"].aggregate([{"$lookup": {"from":"addresses","localField": "address_id","foreignField":"_id","as":"address_details"}}])
data
df = pd.DataFrame(data)
df

,_id,name,age,gender,address_id,address_details
0,1,Amit Sharma,28,Male,101,"[{'_id': 101, 'house_no': 'A-102', 'street': '..."
1,2,Priya Verma,25,Female,102,"[{'_id': 102, 'house_no': 'B-205', 'street': '..."
2,3,Rahul Singh,32,Male,103,"[{'_id': 103, 'house_no': 'C-301', 'street': '..."
3,4,Sneha Patel,27,Female,104,"[{'_id': 104, 'house_no': 'D-405', 'street': '..."
4,5,Rohit Joshi,35,Male,105,"[{'_id': 105, 'house_no': 'E-108', 'street': '..."
5,6,Neha Gupta,24,Female,106,"[{'_id': 106, 'house_no': 'F-212', 'street': '..."
6,7,Vikas Mehta,30,Male,107,"[{'_id': 107, 'house_no': 'G-502', 'street': '..."
7,8,Kavita Rao,29,Female,108,"[{'_id': 108, 'house_no': 'H-304', 'street': '..."
8,9,Arjun Malhotra,38,Male,109,"[{'_id': 109, 'house_no': 'I-601', 'street': '..."
9,10,Pooja Mishra,26,Female,110,"[{'_id': 110, 'house_no': 'J-209', 'street': '..."

In [39]:
data = db["users"].find()
df1 = pd.DataFrame(data)
df1

   _id            name  age  gender  address_id
0    1     Amit Sharma   28    Male         101
1    2     Priya Verma   25  Female         102
2    3     Rahul Singh   32    Male         103
3    4     Sneha Patel   27  Female         104
4    5     Rohit Joshi   35    Male         105
5    6      Neha Gupta   24  Female         106
6    7     Vikas Mehta   30    Male         107
7    8      Kavita Rao   29  Female         108
8    9  Arjun Malhotra   38    Male         109
9   10    Pooja Mishra   26  Female         110

In [41]:
data = db["addresses"].find()
df2 = pd.DataFrame(data)
df2

   _id house_no         street postal_code              landmark       city
0  101    A-102    Vijay Nagar      452010         Scheme No. 54     Indore
1  102    B-205        MG Road      452001               Rajwada     Indore
2  103    C-301   Arera Colony      462016         10 No. Market     Bhopal
3  104    D-405        Palasia      452018              56 Dukan     Indore
4  105    E-108    Civil Lines      482001           Wright Town   Jabalpur
5  106    F-212  Shivaji Nagar      440010          Central Mall     Nagpur
6  107    G-502     Baner Road      411045  Balewadi High Street       Pune
7  108    H-304    Indiranagar      560038         100 Feet Road  Bangalore
8  109    I-601   Andheri West      400058         Infinity Mall     Mumbai
9  110    J-209    Gomti Nagar      226010      Phoenix Palassio    Lucknow

In [42]:
df3 = pd.merge(df1,df2,left_on="address_id",right_on="_id",how="inner")
df3

,_id_x,name,age,gender,address_id,_id_y,house_no,street,postal_code,landmark,city
0,1,Amit Sharma,28,Male,101,101,A-102,Vijay Nagar,452010,Scheme No. 54,Indore
1,2,Priya Verma,25,Female,102,102,B-205,MG Road,452001,Rajwada,Indore
2,3,Rahul Singh,32,Male,103,103,C-301,Arera Colony,462016,10 No. Market,Bhopal
3,4,Sneha Patel,27,Female,104,104,D-405,Palasia,452018,56 Dukan,Indore
4,5,Rohit Joshi,35,Male,105,105,E-108,Civil Lines,482001,Wright Town,Jabalpur
5,6,Neha Gupta,24,Female,106,106,F-212,Shivaji Nagar,440010,Central Mall,Nagpur
6,7,Vikas Mehta,30,Male,107,107,G-502,Baner Road,411045,Balewadi High Street,Pune
7,8,Kavita Rao,29,Female,108,108,H-304,Indiranagar,560038,100 Feet Road,Bangalore
8,9,Arjun Malhotra,38,Male,109,109,I-601,Andheri West,400058,Infinity Mall,Mumbai
9,10,Pooja Mishra,26,Female,110,110,J-209,Gomti Nagar,226010,Phoenix Palassio,Lucknow